load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "block_lib",
    srcs = [
        "block.go",
        "blockchain.go",
    ],
    importpath = "home/pacman/prototype",
)
