---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: internal-app-token-reviewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: internal-app # Replace with your Vault server ServiceAccount name
    namespace: default # Replace with your Vault namespace

