services:
  home-websocket:
    depends_on:
      - redis
    build:
      context: ../..
      dockerfile: docker/websocket/Dockerfile.multistage
      target: websocket-release-stage
    container_name: websocket-server
    hostname: websocket-server
    networks:
      - mynet
    ports:
      - 8080:8080
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynet
volumes:
  redis-data:
networks:
  mynet:
    driver: bridge