services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - websocket-net  
volumes:
  redis-data:
networks:
  websocket-net:
    driver: bridge