services:
  tests:
    image: golang:1.23
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    command: go test -v phase1/server/testcases/main_cockroach_container_test.go