FROM ghcr.io/hybridgroup/opencv:4.12.0 AS local-gocv-image
ENV GOPATH /go
COPY . /go/src/gocv.io/x/gocv/
WORKDIR /go/src/gocv.io/x/gocv
RUN go build -tags example -o /build/gocv_version ./cmd/version/
CMD ["/build/gocv_version"]


FROM local-gocv-image AS gocv-build-stage
WORKDIR /home
COPY go.mod go.sum ./
RUN go mod download
COPY magnet/ffmpeg/ffmpeg-go/gocv/ ./
RUN go build -o main .
ENTRYPOINT ["./main"]
