    version: "3.8"
    services:
      namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.3.4-java11
        hostname: namenode
        ports:
          - "9870:9870"
          - "9000:9000"
        environment:
          - CLUSTER_NAME=test
        env_file:
          - ./hadoop.env
        networks:
          - hadoop-net
      datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.3.4-java11
        hostname: datanode
        ports:
          - "9864:9864"
        environment:
          - SERVICE_PRECONDITION=namenode:9870
        env_file:
          - ./hadoop.env
        depends_on:
          - namenode
        networks:
          - hadoop-net
      resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.3.4-java11
        hostname: resourcemanager
        ports:
          - "8088:8088"
        environment:
          - SERVICE_PRECONDITION=namenode:9870
        env_file:
          - ./hadoop.env
        depends_on:
          - namenode
        networks:
          - hadoop-net
      nodemanager:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.3.4-java11
        hostname: nodemanager
        ports:
          - "8042:8042"
        environment:
          - SERVICE_PRECONDITION=namenode:9870,resourcemanager:8088
        env_file:
          - ./hadoop.env
        depends_on:
          - namenode
          - resourcemanager
        networks:
          - hadoop-net
    networks:
      hadoop-net:
        driver: bridge