apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: observability
manifests:
  rawYaml:   
    - otel.yaml
    - prometheus.yaml       
    - zipkin.yaml 
    - mesh_config.yaml    
    - otel_telemetry.yaml
    - jaeger.yaml
    - skywalking.yaml
    - kiali.yaml
    - bookinfo.yaml
    - bookinfo-gateway.yaml

    
