    version: '3.8'
    services:
      spark-master:
        image: bitnami/spark:latest
        hostname: spark-master
        ports:
          - "8080:8080" # Spark Master UI
          - "7077:7077" # Spark Master Port
        environment:
          - SPARK_MODE=master
          - SPARK_RPC_AUTHENTICATION_ENABLED=no
          - SPARK_RPC_ENCRYPTION_ENABLED=no
          - SPARK_LOCAL_DIRS=/opt/bitnami/spark/tmp
      spark-worker:
        image: bitnami/spark:latest
        hostname: spark-worker
        ports:
          - "8081:8081" # Spark Worker UI
        environment:
          - SPARK_MODE=worker
          - SPARK_MASTER_URL=spark://spark-master:7077
          - SPARK_WORKER_CORES=1
          - SPARK_WORKER_MEMORY=1g
          - SPARK_RPC_AUTHENTICATION_ENABLED=no
          - SPARK_RPC_ENCRYPTION_ENABLED=no
          - SPARK_LOCAL_DIRS=/opt/bitnami/spark/tmp
        depends_on:
          - spark-master