---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gatewayclass-serviceb
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-serviceb
spec:
  gatewayClassName: gatewayclass-serviceb  
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-serviceb
spec:
  parentRefs:
    - name: gateway-serviceb
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: serviceb
          port: 8000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /serviceb
      