---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBd0xURVZNQk1HQTFVRUNnd01aWGhoYlhCc1pTQkoKYm1NdU1SUXdFZ1lEVlFRRERBdGxlR0Z0Y0d4bExtTnZiVEFlRncweU5URXhNamt3TkRRMk5UTmFGdzB5TmpFeApNamt3TkRRMk5UTmFNRGt4R0RBV0JnTlZCQU1NRDNkM2R5NWxlR0Z0Y0d4bExtTnZiVEVkTUJzR0ExVUVDZ3dVClpYaGhiWEJzWlNCdmNtZGhibWw2WVhScGIyNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQzkwVlRTYlNubzBTR09RWFZDS2E3aUxuL0c0M2pJS3hWZjFvZTEyU3JZOFh4b2pRRVFlSWEyNVZLbQpVWHMrZWFJa0xEWnZzVlhIdlJ3OTN2bjRDa29QZXBWcmthd1BtL21UdVppYlR4NVF6S01rNUlSa2xHazNVbDVrCkxrMzRKYXFiUVhZNTIrTlZ6bXdoUTM1NzR5a2Z6RWlZNGJnUE05d05GL2h1RnZTempyZFBvRXZnS1huMUJqNFIKSTIxUFl2WGVCeUhRbU90cEtteDQyclhnRCtOaE93M0VnU1JsYjR1MDhHSHJZWS9oNENjNHhUSE9QWjl1N291NQo2UHdKUG5EVGFwTUFHT1BFNTZDNjQ4THFHemtsUDA0MmJUL3lRZnpKK0ZUaGw1SzJPeVl5anprSDNYRkQ5YkpDClNjNWhMWXlHQzJnQWZZRUlrNlhzRjlraU1uRVhBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBdHYKRVJGTWFkK0RhYjB2dWxlUGpFZlY1OURJdkNFTGNQajBvOUJ5V3Z0emZwN09FaWVmc21LRkhrOS9nb1A1OEo0MQp2ZDFXNnRRMzU1aGp4WVIrN3lDeXdyS0M4NjJ0UDNHZSt6cWE3UVdHSmlJTDdJbmNRWjBBN3NMY3NENXZYd0ZTCi9talVaMVUxa3crR1dTNkZtUDVPYW1uMDZoNThFQVl6dXdjeDNyenh0MnpmWmxJNTJFQndZZlhZYXBjQ0cyb1IKUDJGclk2TFVrUWkwZktqOThxWHBlSGVvWDFJSEJBOHV0VWRjWHhZRFpiUW9jMnBqU1BocTR6TFJhZkQzeEZqZQpiVGZBdVJqNlcveGpCZ291TG96cWt0QUQ1a0xweGNXdTNPd0kzRjRJVzJKbGJOUVJ4Vzk2VnM0K1lEUnAzd09KCjR2Rk5tRkFuMXRpUmNnL2Y5aTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzkwVlRTYlNubzBTR08KUVhWQ0thN2lMbi9HNDNqSUt4VmYxb2UxMlNyWThYeG9qUUVRZUlhMjVWS21VWHMrZWFJa0xEWnZzVlhIdlJ3OQozdm40Q2tvUGVwVnJrYXdQbS9tVHVaaWJUeDVRektNazVJUmtsR2szVWw1a0xrMzRKYXFiUVhZNTIrTlZ6bXdoClEzNTc0eWtmekVpWTRiZ1BNOXdORi9odUZ2U3pqcmRQb0V2Z0tYbjFCajRSSTIxUFl2WGVCeUhRbU90cEtteDQKMnJYZ0QrTmhPdzNFZ1NSbGI0dTA4R0hyWVkvaDRDYzR4VEhPUFo5dTdvdTU2UHdKUG5EVGFwTUFHT1BFNTZDNgo0OExxR3prbFAwNDJiVC95UWZ6SitGVGhsNUsyT3lZeWp6a0gzWEZEOWJKQ1NjNWhMWXlHQzJnQWZZRUlrNlhzCkY5a2lNbkVYQWdNQkFBRUNnZ0VBQWJHaUJrOWN2ZUZMNFlkRkFzWk9IZ3p0MS9wYUJCTkZCQTl0TTVxN1dWSHQKQmNrb1ZzWWZQRXpzbHJrSWJBVE5oUndkNU9qdllUSnNxTzFaOXJRdmVBR1BOQ0FKMUlrcG4zOWEvM0VqemZNZAppNWFSeXpkUWZ3MWk4K3JwTXVDSExBNkNxR2t3RjFQRWFaYnBielZBNkljNy9mS1p0V0phN0Mrb0V3ekNaSmgxClVDcnYvK2RzUzdiL20wbkw5RDZkbCsvenBxR1ZMRTFua2c5c1RBQVF1Ym0wcXpMVzRQakp4WktjdkNGRUZjdkYKNERsM1RTMmhEVk9TNllxVVcrY1I5V0hPcldrZlJCRzd4N0YzcE1iUVpaTHNXWk1IMm9jU2hzY1JqaUxwTE9kYgpHME5QMGI0V3MxWTI4RmFpVG81dlhZV09QTXQxdS9MYUtXQ3JDMjRROFFLQmdRRDNPR1NpdUR0ZnduZExBOEk5CnhyMS9Zb0t3THd1eXZmaHZPR01GenlzZjlEaytsa3N0Nmo1V0g1djNZNnNsZ29WcXcvQy85VWI0NFhVbUFXT0MKbHhmNHpkdnRIdEVpMXc2S1hXdWJWSGhic1UrenlDaFRXbHNnTDJTUllpUXpwWUxqTFlFaEI5eUFKNjhsU25ZTApYWDdCdUpvS0ZwK1JOR1ltWU9SbFlmdmd4d0tCZ1FERWp3L1FlYXlBUmtYLzF2OVJ6ZjhNdjBYaDhpTk5sWkVJCld6NnpCSTB3ODBaY1VWOG1Ec2ZVQjdPUG9aeCt4ZGlDUFR2MDlUcEFsS1JEZEUvU3JaRWVCQTRBZDgxQjV6V1cKYndRbmVrdm1RYXowbXNCU3RJaGNhZ1UxbFVkMk0wbHdNekxUdzFoZC9nbExJNlEwVGJNTzBOVlpGMDM3d3JRZwpGelFralNzOU1RS0JnREhoVC9UQTVVSHA4N1hQK1ZZTGpscHdYdHY3Y2duTGFKL1FLYktYWFNVaVdwWjFMcEFDCkRqZkVRdXpFVUZqT0grc3R3NXFIZTUxbHFBUldEV1RnNVhaTzJzdmFCdXBYcDlobEJ2d2RLL2VjSysrak4vZXgKYUdkekNJQ0k0N01EOXdldE83dVZZWGorQ01tbVgzRGxtVml1elcyeHFOcGNUeXY1S3J3RjdCTXJBb0dBWU5qbwpmdHprck5OelBBcVFCSnVPRnBiTDlQY2NnK2EwN2p3ZkdZK2RqY2ZnSEM2UHhpMjBNZm1WZEtpNWRoRS9pM1JtCmJWekMxZjBuTG9GSnIxR0wxaEZEWU9HbWhkbEpJeFVTSSsxekprR24yV0hDYnoyNmptWkNxTk1qd2M2bFdaNHcKWmZ5ek5xU3JxWlVuSEFwSXRuMFpFZXVVcGY2YVI5R0hCSmQxL1pFQ2dZRUExYkhDYmMweWRWVDNxbVlBc3BLbQora2JOYzlOL05HK2FEZzZta0kyQnVBZ1lQVlQ4M0QyZzBPd2QzZENBS0Z1Y2FNV0VPeU9vRmd4elE3aDlOeWZOCktWZGozdHdrbUNGbFFSY28zbldWd1NtZkpvb3FSNmtUMllYbCt3WVJjOGl2bytlS2NsRWVOWXVxNzdxeDZ4NW0KOHdSUjFjVlFvQ1pmUlF5aHdJaWs1OE09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: "2025-12-04T03:33:42Z"
  name: example-cert
  namespace: default
  resourceVersion: "8618"
  uid: b92fa675-fc5e-45b0-b908-bce189bba01d
type: kubernetes.io/tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gatewayclass-servicea
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-servicea
spec:
  gatewayClassName: gatewayclass-servicea 
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          group: ""
          name: example-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-servicea
spec:
  parentRefs:
    - name: gateway-servicea
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: servicea
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /servicea