otel-trace-pipeline:
  # workers is the number of threads processing data in each pipeline.
  # We recommend same value for all pipelines.
  # default value is 1, set a value based on the machine you are running Data Prepper
  workers: 1
  # delay in milliseconds is how often the worker threads should process data.
  # Recommend not to change this config as we want the entry-pipeline to process as quick as possible
  # default value is 3_000 ms
  delay: "100"
  source:
    otel_trace_source:
      #record_type: event  # Add this when using Data Prepper 1.x. This option is removed in 2.0
      port: 21890
      unframed_requests: true
      path: /ingest/otel-trace-pipeline/v1/traces
      compression: gzip
      output_format: otel
      request_timeout: 15000
      health_check_service: true
      proto_reflection_service: true
      ssl: true
      sslKeyCertChainFile: "/usr/share/data-prepper/config/certs/data-prepper.pem" #public key
      sslKeyFile: "/usr/share/data-prepper/config/certs/data-prepper-key.pem" # private key
      #authentication:
        #unauthenticated: {}
  buffer:
    bounded_blocking:
      # buffer_size is the number of ExportTraceRequest from otel-collector the Data Prepper should hold in memory. 
      # We recommend to keep the same buffer_size for all pipelines. 
      # Make sure you configure sufficient heap
      # default value is 512
      buffer_size: 500000
      # This is the maximum number of request each worker thread will process within the delay.
      # Default is 8.
      # Make sure buffer_size >= workers * batch_size
      batch_size: 10000
  sink:
    - stdout:
    - pipeline:
        name: raw-trace-pipeline
    - pipeline:
        name: service-map-pipeline

raw-trace-pipeline:
  # Configure same as the otel-trace-pipeline
  workers: 1
  # We recommend using the default value for the raw-trace-pipeline.
  delay: 3000
  source:
    pipeline: 
      name: otel-trace-pipeline
  buffer:
    bounded_blocking:
      # Configure the same value as in entry-pipeline
      # Make sure you configure sufficient heap
      # The default value is 512
      buffer_size: 500000
      # The raw processor does bulk request to your OpenSearch sink, so configure the batch_size higher.
      # If you use the recommended otel-collector setup each ExportTraceRequest could contain max 50 spans. https://github.com/opensearch-project/data-prepper/tree/v0.7.x/deployment/aws
      # With 64 as batch size each worker thread could process upto 3200 spans (64 * 50)
      batch_size: 10000
  processor:
    - otel_traces:
    # Optional: only if you want the group-filler stage.
    - otel_trace_group:
        hosts: [ "https://node-0.example.com:9200" ]
        #insecure: true
        username: admin
        password: "Skype@123"
        # Add a certificate file if you are accessing an OpenSearch cluster with a self-signed certificate  
        cert: /usr/share/data-prepper/config/certs/opensearch-root-ca.pem
        # If you are connecting to an Amazon OpenSearch Service domain without
        # Fine-Grained Access Control, enable these settings. Comment out the
        # username and password above.
        #aws_sigv4: true
        #aws_region: us-east-1
  sink:
    - stdout:
    - opensearch:
        hosts: [ "https://node-0.example.com:9200" ]
        index_type: trace-analytics-raw
        #insecure: true
        username: admin
        password: "Skype@123"
        # Add a certificate file if you are accessing an OpenSearch cluster with a self-signed certificate  
        cert: /usr/share/data-prepper/config/certs/opensearch-root-ca.pem
        # If you are connecting to an Amazon OpenSearch Service domain without
        # Fine-Grained Access Control, enable these settings. Comment out the
        # username and password above.
        #aws_sigv4: true
        #aws_region: us-east-1

service-map-pipeline:
  workers: 1
  delay: 100
  source:
    pipeline: 
      name: otel-trace-pipeline
  processor:
    - service_map:
        # The window duration is the maximum length of time the data prepper stores the most recent trace data to evaluvate service-map relationships.
        # The default is 3 minutes, this means we can detect relationships between services from spans reported in last 3 minutes.
        # Set higher value if your applications have higher latency.
        window_duration: 180
  buffer:
    bounded_blocking:
      # buffer_size is the number of ExportTraceRequest from otel-collector the Data Prepper should hold in memory. 
      # We recommend to keep the same buffer_size for all pipelines. 
      # Make sure you configure sufficient heap
      # default value is 512
      buffer_size: 500000
      # This is the maximum number of request each worker thread will process within the delay.
      # Default is 8.
      # Make sure buffer_size >= workers * batch_size
      batch_size: 10000
  sink:
    - stdout:
    - opensearch:
        hosts: [ "https://node-0.example.com:9200" ]
        index_type: trace-analytics-service-map
        # Change to your credentials
        username: admin
        password: "Skype@123"
        # Add a certificate file if you are accessing an OpenSearch cluster with a self-signed certificate  
        cert: /usr/share/data-prepper/config/certs/opensearch-root-ca.pem
        # If you are connecting to an Amazon OpenSearch Service domain without
        # Fine-Grained Access Control, enable these settings. Comment out the
        # username and password above.
        #aws_sigv4: true
        #aws_region: us-east-1