apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: vault
      containers:
        - name: app
          image: thuyltm2201/simple-vault-client:latest
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: 'http://vault:8200'
            - name: JWT_PATH
              value: '/var/run/secrets/kubernetes.io/serviceaccount/token'
            - name: SERVICE_PORT
              value: '8080'
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: k8s-audience-token
      volumes:
      - name: k8s-audience-token
        projected:
          sources:
          - serviceAccountToken:
              audience: "https://kubernetes.default.svc.cluster.local"
              expirationSeconds: 3600
              path: token 