FROM golang:1.25.5-alpine AS builder
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
WORKDIR /home
COPY go.mod go.sum ./
RUN go mod download
COPY spiral/opentelemetry-contrib/dice spiral/opentelemetry-contrib/dice
RUN go build -o main spiral/opentelemetry-contrib/dice/*.go

FROM alpine:3.17 AS opentelemetry-service-demo
COPY --from=builder /home/main main
EXPOSE 8000
CMD ["./main"]

