apiVersion: v1
data:
  otel-collector-config.yml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "jaeger.default.svc.cluster.local:4317"
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: "http://prometheus:9090/api/v1/otlp"
        tls:
          insecure: true

    processors:
      batch:
      attributes/example:
        actions:
          - key: example_field
            action: insert
            value: Hello from the OpenTelemetry Collector

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/prometheus, debug]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fask-test
  labels:
    app.kubernetes.io/managed-by: Helm
  name: otelcol-configmap
