version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0 # Replace with desired version
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false # For development, disable security
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory as needed
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persist data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - mynet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0 # Replace with desired version
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - mynet
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  mynet:
    driver: bridge