FROM golang:1.23 AS http-build-stage
WORKDIR /home
COPY go.mod go.sum ./
RUN go mod download
COPY phase1/echo/ phase1/echo/
RUN go build -o main ./phase1/echo

# Deploy the application binary into a clean image
FROM golang:1.23 AS http-release-stage
WORKDIR /
COPY --from=http-build-stage /home/ ./
EXPOSE 9090
ENTRYPOINT ["./main"]