FROM golang:1.25-alpine AS http-build-stage
WORKDIR /home
COPY go.mod go.sum ./
RUN go mod download
COPY phase1/echo/ phase1/echo/
RUN go build -o main ./phase1/echo

# Deploy the application binary into a clean image
FROM alpine:latest AS http-release-stage
# Install curl and remove the apk cache to minimize image size
RUN apk --no-cache add curl
CMD ["curl", "https://www.google.com"]
WORKDIR /
COPY --from=http-build-stage /home/ ./
EXPOSE 9090
ENTRYPOINT ["./main"]