services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    hostname: mediamtx
    networks:
      - mynet
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
      - 8189:8189/udp
    env_file:
      - .env
networks:
  mynet:
    driver: bridge